<?php 

class Country_model extends CI_Model
{
	public function __construct()
	{
		parent::__construct();
	}
    
    public function get_countries($region)
    {
        $data['africa'] = array(
         '' => '-- Choose Country --',
         'algeria' => 'Algeria',
         'angola' => 'Angola',
         'benin' => 'Benin',
         'botswana' => 'Botswana',
         'burkinofaso' => 'Burkino Faso',
         'burundi' => 'Burundi', 
         'cameroon' => 'Cameroon',
         'centralafricanrepublic' => 'Central African Rep.',
         'chad' => 'Chad',        
         'comoros' => 'Comoros',
         'congo' => 'Congo',
         'cotedivore' => 'Côte d\'Ivore',
         'democraticrepublicofcongo' => 'Dem. Rep. of Congo',
         'djibouti' => 'Djibouti',
         'egypt' => 'Egypt',
         'equatorialguinea' => 'Equatorial Guinea',
         'eritrea' => 'Eritrea',
         'ethiopia' => 'Etiopia',
         'gabon' => 'Gabon',
         'gambia' => 'Gambia',
         'ghana' => 'Ghana',
         'guinea' => 'Guinea',
         'guineabissau' => 'Guinea Bissau',
         'kenya' => 'Kenya',
         'lesotho' => 'Lesotho',
         'liberia' => 'Liberia',
         'libya' => 'Libya',
         'madagascar' => 'Madagascar',
         'malawi' => 'Malawi',
         'mali' => 'Mali',
         'mauritania' => 'Mauritania',
         'mauritius' => 'Mauritius',
         'morocco' => 'Morocco',
         'mozambique' => 'Mozambique',
         'namibia' => 'Namibia',
         'niger' => 'Niger',
         'nigeria' => 'Nigeria',
         'rwanda' => 'Rwanda',
         'saotomeandprincipe' => 'São Tomé and Príncipe',
         'senegal' => 'Senegal',
         'seychelles' => 'Seychelles',
         'sierraleone' => 'Sierra Leone',
         'somalia' => 'Somalia',
         'southafrica' => 'South Africa',
         'southsudan' => 'South Sudan',
         'sudan' => 'Sudan',
         'swaziland' => 'Swaziland',
         'tanzania' => 'Tanzania',
         'togo' => 'Togo',
         'tunesia' => 'Tunesia',
         'uganda' => 'Uganda',
         'westernsahara' => 'Western Sahara',
         'zambia' => 'Zambia',
         'zimbabwe' => 'Zimbabwe'
        );
    
         $data['asia'] = array(
         '' => '-- Choose Country --',
             'afghanistan' => 'Afghanistan',
             'bangladesh' => 'Bangladesh',
             'bhutan' => 'Bhutan',
             'burma' => 'Burma',
             'cambodja' => 'Cambodja',
             'china' => 'China',
             'india' => 'India',
             'iran' => 'Iran',
             'iraq' => 'Iraq',
             'israel' => 'Israel',
             'japan' => 'Japan',
             'jordan' => 'Jordan',
             'kazakhstan' => 'Kazakhstan',
             'kuwait' => 'Kuwait',
             'kyrgyzstan' => 'Kyrgyzstan',
             'laos' => 'Laos',
             'lebanon' => 'Lebanon',
             'malaysia' => 'Malaysia',
             'maldives' => 'Maldives',
             'mongolia' => 'Mongolia',
             'nepal' => 'Nepal',
             'northkorea' => 'North Korea',
             'oman' => 'Oman',
             'pakistan' => 'Pakistan',
             'philippines' => 'Afghanistan',
             'qatar' => 'Qatar',
             'saudiarabia' => 'Saudi Arabia',
             'southkorea' => 'South Korea',
             'srilanka' => 'Sri Lanka',
             'syria' => 'Syria',
             'taiwan' => 'Taiwan',
             'tajikistan' => 'Tajikistan',
             'thailand' => 'Thailand',
             'turkey' => 'Turkey',
             'turkmenistan' => 'Turkmenistan',
             'uae' => 'United Arab Emirates',
             'uzbekistan' => 'Uzbekistan',
             'vietnam' => 'Vietnam',
             'yemen' => 'Yemen',
         );
         
         $data['caribbean'] = array(
         '' => '-- Choose Country --',
             'anguilla' => 'Anguilla',
             'antigua' => 'Antigua',
             'aruba' => 'Aruba',
             'bahamas' => 'Bahamas',
             'barbados' => 'Barbados',
             'barbuda' => 'Barbuda',
             'bonaire' => 'Bonaire',
             'britishvirginislands' => 'British Virgin Islands',
             'caymanislands' => 'Cayman Islands',
             'cuba' => 'Cuba',
             'curacao' => 'Curacao',
             'dominica' => 'Dominica',
             'dominicanrepublic' => 'Dominican Republic',
             'grenada' => 'Grenada',
             'grenadines' => 'Grenadines',
             'guadeloupe' => 'Guadeloupe',
             'haiti' => 'Haiti',
             'jamaica' => 'Jamaica',
             'martinique' => 'Martinique',
             'montserrat' => 'Montserrat',
             'puertorico' => 'Puerto Rico',
             'saba' => 'Saba',
             'saintbarthelemy' => 'Saint Barthélemy',
             'saintkittsandnevis' => 'Saint Kitts and Nevis',
             'saintlucia' => 'Saint Lucia',
             'saintvincent' => 'Saint Vincent',
             'sinteustatius' => 'Sint Eustatius',
             'sintmaarten' => 'Sint Maarten',
             'trinidadandtobago' => 'Trinidad and Tobago',
             'turkandcaicos' => 'Turk and Caicos',     
             'virginislands' => 'Virgin Islands'    
         );
        
        $data['central_america'] = array(
        '' => '-- Choose Country --',
             'belize' => 'Belize',
             'colombia' => 'Colombia',
             'costarica' => 'Costa Rica',
             'elsalvador' => 'El Salvador',
             'frenchguiana' => 'French Guiana',
             'guatemala' => 'Guatemala',
             'guyana' => 'Guyana',
             'honduras' => 'Honduras',
             'mexico' => 'Mexico',
             'nicaragua' => 'Nicaragua',
             'panama' => 'Panama',
             'suriname' => 'Suriname',
             'venezuela' => 'Venezuela'
         );
        
         $data['europe'] = array(
         '' => '-- Choose Country --',
             'albania' => 'Albania',
             'armenia' => 'Armenia',
             'austria' => 'Austria',
             'azerbaijan' => 'Azerbaijan',
             'belarus' => 'Belarus',
             'belgium' => 'Belgium',
             'bosniaherzegovina' => 'Bosnia Herzegovina',
             'bulgaria' => 'Bulgaria',
             'croatia' => 'Croatia',
             'czechrepublic' => 'Czech Republic',
             'denmark' => 'Denmark',
             'estonia' => 'Estonia',
             'finland' => 'Finland',
             'france' => 'France',
             'georgiaus' => 'Georgia',
             'germany' => 'Germany',
             'greece' => 'Greece',
             'hungary' => 'Hungary',
             'iceland' => 'Iceland',
             'ireland' => 'Ireland',
             'italy' => 'Italy',     
             'latvia' => 'Latvia',
             'lithuania' => 'Lithuania',
             'luxembourg' => 'Luxembourg',
             'macedonia' => 'Macedonia',
             'moldova' => 'Moldova',
             'netherlands' => 'Netherlands',
             'norway' => 'Norway',
             'poland' => 'Poland',
             'portugal' => 'Portugal',
             'romania' => 'Romania',
             'serbia' => 'Serbia',
             'slovakia' => 'Slovakia',
             'slovenia' => 'Slovenia',
             'spain' => 'Spain',
             'sweden' => 'Sweden',
             'switzerland' => 'Switzerland',
             'ukraine' => 'Ukraine',
             'unitedkingdom' => 'United Kingdom',
             'vaticancity' => 'Vatican City'
         ); 
         
         $data['north_america'] = array(
         '' => '-- Choose Country --',
             'canada' => 'Canada',
             'greenland' => 'Greenland',
             'unitedstatesofamerica' => 'United states of America'
         );
         
          $data['oceania'] = array(
          '' => '-- Choose Country --',
             'cookislands' => 'Cook Islands',
             'fiji' => 'Fiji',
             'frenchpolynesia' => 'French Polynesia',
             'kiribati' => 'Kiribati',
             'marshallislands' => 'Marshall Islands',
             'nauru' => 'Nauru',
             'newzealand' => 'New Zealand',
             'niue' => 'Niue',
             'northernmarianaislands' => 'Northern Mariana Islands',
             'papuanewguinea' => 'Papua New Guinea',
             'pitcairnislands' => 'Pitcairn Islands',
             'samoa' => 'Samoa',
             'solomonislands' => 'Solomon Islands',
             'tonga' => 'Tonga',
             'tuvalu' => 'Tuvalu',
             'vanuatu' => 'Vanuatu'    
         );
         
         $data['south_america'] = array(
         '' => '-- Choose Country --',
             'argentina' => 'Argentina',
             'bolivia' => 'Bolivia',
             'brazil' => 'Brazil',
             'chile' => 'Chile',
             'equador' => 'Equador',
             'falklandislands' => 'Falkland Islands',
             'paraguay' => 'Paraguay',
             'peru' => 'Peru',
             'uruguay' => 'Uruguay'
         );
        
        return $data[$region]; 
    }
}