<?php 

class Country_model extends CI_Model
{
	public function __construct()
	{
		parent::__construct();
	}
    
    public function get_countries($region)
    {
        $data['africa'] = array(
            '' => '-- Choose Country --',
            'algeria' => 'Algeria',
            'angola' => 'Angola',
            'benin' => 'Benin',
            'botswana' => 'Botswana',
            'burkino_faso' => 'Burkino Faso',
            'burundi' => 'Burundi', 
            'cameroon' => 'Cameroon',
            'cape_verde' => 'Cape Verde',
            'central_african_republic' => 'Central African Rep.',
            'chad' => 'Chad',        
            'comoros' => 'Comoros',
            'congo' => 'Congo',
            'cote_d_ivore' => 'Cote d Ivore',
            'democratic_republic_of_congo' => 'Dem. Rep. of Congo',
            'djibouti' => 'Djibouti',
            'egypt' => 'Egypt',
            'equatorial_guinea' => 'Equatorial Guinea',
            'eritrea' => 'Eritrea',
            'ethiopia' => 'Etiopia',
            'gabon' => 'Gabon',
            'gambia' => 'Gambia',
            'ghana' => 'Ghana',
            'guinea' => 'Guinea',
            'guinea_bissau' => 'Guinea Bissau',
            'kenya' => 'Kenya',
            'lesotho' => 'Lesotho',
            'liberia' => 'Liberia',
            'libya' => 'Libya',
            'madagascar' => 'Madagascar',
            'malawi' => 'Malawi',
            'mali' => 'Mali',
            'mauritania' => 'Mauritania',
            'mauritius' => 'Mauritius',
            'morocco' => 'Morocco',
            'mozambique' => 'Mozambique',
            'namibia' => 'Namibia',
            'niger' => 'Niger',
            'nigeria' => 'Nigeria',
            'rwanda' => 'Rwanda',
            'sao_tome_and_principe' => 'Sao Tome and Principe',
            'senegal' => 'Senegal',
            'seychelles' => 'Seychelles',
            'sierra_leone' => 'Sierra Leone',
            'somalia' => 'Somalia',
            'southafrica' => 'South Africa',
            'southsudan' => 'South Sudan',
            'sudan' => 'Sudan',
            'swaziland' => 'Swaziland',
            'tanzania' => 'Tanzania',
            'togo' => 'Togo',
            'tunesia' => 'Tunesia',
            'uganda' => 'Uganda',
            'western_sahara' => 'Western Sahara',
            'zambia' => 'Zambia',
            'zanzibar' => 'Zanzibar',
            'zimbabwe' => 'Zimbabwe'
        );

        $data['asia'] = array(
            '' => '-- Choose Country --',
            'afghanistan' => 'Afghanistan',
            'bangladesh' => 'Bangladesh',
            'bhutan' => 'Bhutan',
            'brunei' => 'Brunei',
            'burma' => 'Burma',
            'cambodia' => 'Cambodia',
            'china' => 'China',
            'east_timor' => 'East Timor',
            'india' => 'India',
            'iran' => 'Iran',
            'iraq' => 'Iraq',
            'israel' => 'Israel',
            'japan' => 'Japan',
            'jordan' => 'Jordan',
            'kazakhstan' => 'Kazakhstan',
            'kuwait' => 'Kuwait',
            'kyrgyzstan' => 'Kyrgyzstan',
            'laos' => 'Laos',
            'lebanon' => 'Lebanon',
            'malaysia' => 'Malaysia',
            'maldives' => 'Maldives',
            'mongolia' => 'Mongolia',
            'nepal' => 'Nepal',
            'north_korea' => 'North Korea',
            'oman' => 'Oman',
            'pakistan' => 'Pakistan',
            'philippines' => 'Philippines',
            'qatar' => 'Qatar',
            'saudi_arabia' => 'Saudi Arabia',
            'south_korea' => 'South Korea',
            'srilanka' => 'Sri Lanka',
            'syria' => 'Syria',
            'taiwan' => 'Taiwan',
            'tajikistan' => 'Tajikistan',
            'thailand' => 'Thailand',
            'turkey' => 'Turkey',
            'turkmenistan' => 'Turkmenistan',
            'uae' => 'United Arab Emirates',
            'uzbekistan' => 'Uzbekistan',
            'vietnam' => 'Vietnam',
            'yemen' => 'Yemen',
        );

        $data['caribbean'] = array(
            '' => '-- Choose Country --',
            'anguilla' => 'Anguilla',
            'antigua' => 'Antigua',
            'aruba' => 'Aruba',
            'bahamas' => 'Bahamas',
            'barbados' => 'Barbados',
            'barbuda' => 'Barbuda',
            'bonaire' => 'Bonaire',
            'british_virgin_islands' => 'British Virgin Islands',
            'cayman_islands' => 'Cayman Islands',
            'cuba' => 'Cuba',
            'curacao' => 'Curacao',
            'dominica' => 'Dominica',
            'dominican_republic' => 'Dominican Republic',
            'grenada' => 'Grenada',
            'grenadines' => 'Grenadines',
            'guadeloupe' => 'Guadeloupe',
            'haiti' => 'Haiti',
            'jamaica' => 'Jamaica',
            'martinique' => 'Martinique',
            'montserrat' => 'Montserrat',
            'puerto_rico' => 'Puerto Rico',
            'saba' => 'Saba',
            'saint_barthelemy' => 'Saint Barthelemy',
            'saint_kitts_and_nevis' => 'Saint Kitts and Nevis',
            'saint_lucia' => 'Saint Lucia',
            'saint_martin' => 'Saint Martin',
            'saint_vincent' => 'Saint Vincent',
            'sint_eustatius' => 'Sint Eustatius',
            'trinidad_and_tobago' => 'Trinidad and Tobago',
            'turk_and_caicos' => 'Turk and Caicos',     
            'us_virgin_islands' => 'U.S. Virgin Islands'    
        );

        $data['central_america'] = array(
            '' => '-- Choose Country --',
            'belize' => 'Belize',
            'colombia' => 'Colombia',
            'costa_rica' => 'Costa Rica',
            'el_salvador' => 'El Salvador',
            'french_guiana' => 'French Guiana',
            'guatemala' => 'Guatemala',
            'guyana' => 'Guyana',
            'honduras' => 'Honduras',
            'mexico' => 'Mexico',
            'nicaragua' => 'Nicaragua',
            'panama' => 'Panama',
            'suriname' => 'Suriname',
            'venezuela' => 'Venezuela'
        );

        $data['europe'] = array(
            '' => '-- Choose Country --',
            'albania' => 'Albania',
            'armenia' => 'Armenia',
            'austria' => 'Austria',
            'azerbaijan' => 'Azerbaijan',
            'belarus' => 'Belarus',
            'belgium' => 'Belgium',
            'bosnia_herzegovina' => 'Bosnia Herzegovina',
            'bulgaria' => 'Bulgaria',
            'croatia' => 'Croatia',
            'cyprus' => 'Cyprus',
            'czech_republic' => 'Czech Republic',
            'denmark' => 'Denmark',
            'estonia' => 'Estonia',
            'finland' => 'Finland',
            'france' => 'France',
            'georgia_us' => 'Georgia',
            'germany' => 'Germany',
            'greece' => 'Greece',
            'hungary' => 'Hungary',
            'iceland' => 'Iceland',
            'ireland' => 'Ireland',
            'italy' => 'Italy',     
            'latvia' => 'Latvia',
            'lithuania' => 'Lithuania',
            'luxembourg' => 'Luxembourg',
            'macedonia' => 'Macedonia',
            'moldova' => 'Moldova',
            'netherlands' => 'Netherlands',
            'norway' => 'Norway',
            'poland' => 'Poland',
            'portugal' => 'Portugal',
            'romania' => 'Romania',
            'serbia' => 'Serbia',
            'slovakia' => 'Slovakia',
            'slovenia' => 'Slovenia',
            'spain' => 'Spain',
            'sweden' => 'Sweden',
            'switzerland' => 'Switzerland',
            'ukraine' => 'Ukraine',
            'united_kingdom' => 'United Kingdom',
            'vatican_city' => 'Vatican City'
        ); 
        
        $data['middle_east'] = array(
            '' => '-- Choose Country --',
            'cyprus' => 'Cyprus',
     		'egypt' => 'Egypt',
			'iran' => 'Iran',
			'iraq' => 'Iraq',
			'israel' => 'Israel',
			'jordan' => 'Jordan',
			'kuwait' => 'Kuwait',
			'lebanon' => 'Lebanon',		
			'oman' => 'Oman',
			'qatar' => 'Qatar',
			'saudi_arabia' => 'Saudi Arabia',
			'syria' => 'Syria',
			'turkey' => 'Turkey',
			'uae' => 'United Arab Emirates',
			'yemen' => 'Yemen',

        ); 

        $data['north_america'] = array(
            '' => '-- Choose Country --',
            'canada' => 'Canada',
            'greenland' => 'Greenland',
            'usa' => 'United states of America'
        );

        $data['oceania'] = array(
            '' => '-- Choose Country --',
            'australia' => 'Australia',
            'cook_islands' => 'Cook Islands',
            'fiji' => 'Fiji',
            'french_polynesia' => 'French Polynesia',
            'indonesia' => 'Indonesia',
            'kiribati' => 'Kiribati',
            'marshall_islands' => 'Marshall Islands',
            'nauru' => 'Nauru',
            'new_zealand' => 'New Zealand',
            'niue' => 'Niue',
            'northern_mariana_islands' => 'Northern Mariana Islands',
            'papua_new_guinea' => 'Papua New Guinea',
            'pitcairn_islands' => 'Pitcairn Islands',
            'samoa' => 'Samoa',
            'solomon_islands' => 'Solomon Islands',
            'tonga' => 'Tonga',
            'tuvalu' => 'Tuvalu',
            'us_samoa' => 'U.S. Samoa',  
            'vanuatu' => 'Vanuatu'    

        );

        $data['south_america'] = array(
            '' => '-- Choose Country --',
            'argentina' => 'Argentina',
            'bolivia' => 'Bolivia',
            'brazil' => 'Brazil',
            'chile' => 'Chile',
            'equador' => 'Equador',
            'falkland_islands' => 'Falkland Islands',
            'paraguay' => 'Paraguay',
            'peru' => 'Peru',
            'uruguay' => 'Uruguay'
        );
        
        return $data[$region]; 
    }
    
    public function country_to_controller($arg)
    {
        $data = array(
        	'algeria' 	=> 'africa_countries',
			'angola' 	=> 'africa_countries',
			'benin' 	=> 'africa_countries',
			'botswana' => 'africa_countries',
			'burkino_faso' => 'africa_countries',
			'burundi' => 'africa_countries' ,
			'cameroon' => 'africa_countries',			
			'cape_verde' => 'africa_countries',
			'central_african_republic' => 'africa_countries',
			'chad' => 'africa_countries' ,
			'comoros' => 'africa_countries',
			'congo' => 'africa_countries',
			'cote_d_ivore' => 'africa_countries',
			'democratic_republic_of_congo' => 'africa_countries',
			'djibouti' => 'africa_countries',
			'egypt' => 'africa_countries',
			'equatorial_guinea' => 'africa_countries',
			'eritrea' => 'africa_countries',
			'ethiopia' => 'africa_countries',
			'gabon' => 'africa_countries',
			'gambia' => 'africa_countries',
			'ghana' => 'africa_countries',
			'guinea' => 'africa_countries',
			'guinea_bissau' => 'africa_countries',
			'kenya' => 'africa_countries',
			'lesotho' => 'africa_countries',
			'liberia' => 'africa_countries',
			'libya' => 'africa_countries',
			'madagascar' => 'africa_countries',
			'malawi' => 'africa_countries',
			'mali' => 'africa_countries',
			'mauritania' => 'africa_countries',
			'mauritius' => 'africa_countries',
			'morocco' => 'africa_countries',
			'mozambique' => 'africa_countries',
			'namibia' => 'africa_countries',
			'niger' => 'africa_countries',
			'nigeria' => 'africa_countries',
			'rwanda' => 'africa_countries',
			'sao_tome_and_principe' => 'africa_countries',
			'senegal' => 'africa_countries',
			'seychelles' => 'africa_countries',
			'sierra_leone' => 'africa_countries',
			'somalia' => 'africa_countries',
			'south_africa' => 'africa_countries',
			'south_sudan' => 'africa_countries',
			'sudan' => 'africa_countries',
			'swaziland' => 'africa_countries',
			'tanzania' => 'africa_countries',
			'togo' => 'africa_countries',
			'tunesia' => 'africa_countries',
			'uganda' => 'africa_countries',
			'western_sahara' => 'africa_countries',
			'zambia' => 'africa_countries',
			'zimbabwe' => 'africa_countries',
			'zanzibar' => 'africa_countries',

			'afghanistan' => 'asia_countries',
			'bangladesh' => 'asia_countries',
			'bhutan' => 'asia_countries',
			'brunei' => 'asia_countries',
			'burma' => 'asia_countries',
			'cambodia' => 'asia_countries',
			'china' => 'asia_countries',
			'east_timor' => 'asia_countries',
			'india' => 'asia_countries',
			'iran' => 'asia_countries',
			'iraq' => 'asia_countries',
			'israel' => 'asia_countries',
			'japan' => 'asia_countries',
			'jordan' => 'asia_countries',
			'kazakhstan' => 'asia_countries',
			'kuwait' => 'asia_countries',
			'kyrgyzstan' => 'asia_countries',
			'laos' => 'asia_countries',
			'lebanon' => 'asia_countries',
			'malaysia' => 'asia_countries',
			'maldives' => 'asia_countries',
			'mongolia' => 'asia_countries',
			'nepal' => 'asia_countries',
			'north_korea' => 'asia_countries',
			'oman' => 'asia_countries',
			'pakistan' => 'asia_countries',
			'philippines' => 'asia_countries',
			'qatar' => 'asia_countries',
			'saudi_arabia' => 'asia_countries',
			'south_korea' => 'asia_countries',
			'sri_lanka' => 'asia_countries',
			'syria' => 'asia_countries',
			'taiwan' => 'asia_countries',
			'tajikistan' => 'asia_countries',
			'thailand' => 'asia_countries',
			'turkey' => 'asia_countries',
			'turkmenistan' => 'asia_countries',
			'uae' => 'asia_countries',
			'uzbekistan' => 'asia_countries',
			'vietnam' => 'asia_countries',
			'yemen' => 'asia_countries',


			'anguilla' => 'caribbean_countries',
			'antigua' => 'caribbean_countries',
			'aruba' => 'caribbean_countries',
			'bahamas' => 'caribbean_countries',
			'barbados' => 'caribbean_countries',
			'barbuda' => 'caribbean_countries',
			'bonaire' => 'caribbean_countries',
			'british_virgin_islands' => 'caribbean_countries',
			'cayman_islands' => 'caribbean_countries',
			'cuba' => 'caribbean_countries',
			'curacao' => 'caribbean_countries',
			'dominica' => 'caribbean_countries',
			'dominican_republic' => 'caribbean_countries',
			'grenada' => 'caribbean_countries',
			'grenadines' => 'caribbean_countries',
			'guadeloupe' => 'caribbean_countries',
			'haiti' => 'caribbean_countries',
			'jamaica' => 'caribbean_countries',
			'martinique' => 'caribbean_countries',
			'montserrat' => 'caribbean_countries',
			'puerto_rico' => 'caribbean_countries',
			'saba' => 'caribbean_countries',
			'saint_barthelemy' => 'caribbean_countries',
			'saint_kitts_and_nevis' => 'caribbean_countries',
			'saint_lucia' => 'caribbean_countries',
			'saint_martin' => 'caribbean_countries',
			'saint_vincent' => 'caribbean_countries',
			'sint_eustatius' => 'caribbean_countries',
			'trinidad_and_tobago' => 'caribbean_countries',
			'turk_and_caicos' => 'caribbean_countries',
			'us_virgin_islands' => 'caribbean_countries',


			'belize' => 'central_america_countries',
			'colombia' => 'central_america_countries',
			'costa_rica' => 'central_america_countries',
			'el_salvador' => 'central_america_countries',
			'french_guiana' => 'central_america_countries',
			'guatemala' => 'central_america_countries',
			'guyana' => 'central_america_countries',
			'honduras' => 'central_america_countries',
			'mexico' => 'central_america_countries',
			'nicaragua' => 'central_america_countries',
			'panama' => 'central_america_countries',
			'suriname' => 'central_america_countries',
			'venezuela' => 'central_america_countries',


			'albania' => 'europe_countries',		
			'armenia' => 'europe_countries' ,				
			'austria' => 'europe_countries' ,				
			'azerbaijan' => 'europe_countries', 		
			'belarus'  => 'europe_countries'	,			
			'belgium' 	 => 'europe_countries'	,		
			'bosnia_herzegovina'  => 'europe_countries',
			'bulgaria' 	 => 'europe_countries'	,
			'croatia' 		 => 'europe_countries'	,
			'cyprus' 		 => 'europe_countries'	,
			'czech_republic'  => 'europe_countries'	,
			'denmark' 		 => 'europe_countries',		
			'estonia' 	 => 'europe_countries',
			'finland' 	 => 'europe_countries',
			'france' 			 => 'europe_countries',	
			'georgia_us' 		 => 'europe_countries',
			'germany' 				 => 'europe_countries',
			'greece' 				 => 'europe_countries',
			'hungary' 				 => 'europe_countries',
			'iceland' 				 => 'europe_countries',
			'ireland' 				 => 'europe_countries',
			'italy' 				 => 'europe_countries',
			'latvia' 				 => 'europe_countries',
			'lithuania' 		 => 'europe_countries',
			'luxembourg' 		 => 'europe_countries',
			'macedonia' 		 => 'europe_countries',
			'moldova' 			 => 'europe_countries',	
			'netherlands' 		 => 'europe_countries',
			'norway' 				 => 'europe_countries',
			'poland' 				 => 'europe_countries',
			'portugal' 		 => 'europe_countries',
			'romania' 				 => 'europe_countries',
			'serbia' 				 => 'europe_countries',
			'slovakia' 		 => 'europe_countries',
			'slovenia' 		 => 'europe_countries',
			'spain' 				 => 'europe_countries',
			'sweden' 				 => 'europe_countries',
			'switzerland' 		 => 'europe_countries',
			'ukraine' 				 => 'europe_countries',
			'united_kingdom' 	 => 'europe_countries',
			'vatican_city' 		 => 'europe_countries',

			'canada' => 'north_america_countries',
			'greenland' => 'north_america_countries',
			'usa' => 'regions',


			'australia' => 'regions',
			'cook_islands' => 'oceania_countries',
			'fiji' => 'oceania_countries',
			'french_polynesia' => 'oceania_countries',
			'indonesia' => 'regions',
			'kiribati' => 'oceania_countries',
			'marshall_islands' => 'oceania_countries',
			'nauru' => 'oceania_countries',
			'new_zealand' => 'oceania_countries',
			'niue' => 'oceania_countries',
			'northernmarianaislands' => 'oceania_countries',
			'papua_new_guinea' => 'oceania_countries',
			'pitcairn_islands' => 'oceania_countries',
			'samoa' => 'oceania_countries',
			'solomon_islands' => 'oceania_countries',
			'tonga' => 'oceania_countries',
			'tuvalu' => 'oceania_countries',
			'us_samoa' => 'oceania_countries',
			'vanuatu' => 'oceania_countries',

			'argentina' => 'south_america_countries',
			'bolivia' => 'south_america_countries',
			'brazil' => 'south_america_countries',
			'chile' => 'south_america_countries',
			'equador' => 'south_america_countries',
			'falkland_islands' => 'south_america_countries',
			'paraguay' => 'south_america_countries',
			'peru' => 'south_america_countries',
			'uruguay' => 'south_america_countries'
        );
         
		return $data[$arg];
    }
}