
// This file has been generated by the GUI designer. Do not modify.
namespace MyRsa
{
	public partial class MainWindow
	{
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Button button1;
		private global::Gtk.FileChooserButton filechooserbutton2;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TextView textview4;
		private global::Gtk.Button button3;
		private global::Gtk.Button button4;
		private global::Gtk.Statusbar statusbar1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textview2;
		private global::Gtk.Label label4;
		private global::Gtk.Label label3;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView textview3;
		private global::Gtk.Entry entry1;
		private global::Gtk.Entry entry2;
		private global::Gtk.Label label5;
		private global::Gtk.Label label6;
		private global::Gtk.Label label7;
		private global::Gtk.Entry entry3;
		private global::Gtk.Entry entry4;
		private global::Gtk.Label label8;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MyRsa.MainWindow
			this.Name = "MyRsa.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MyRsa.MainWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button ();
			this.button1.WidthRequest = 80;
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("Exit");
			this.fixed1.Add (this.button1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button1]));
			w1.X = 680;
			w1.Y = 296;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.filechooserbutton2 = new global::Gtk.FileChooserButton (
				global::Mono.Unix.Catalog.GetString("Select A File"),
				((global::Gtk.FileChooserAction)(0))
			);
			this.filechooserbutton2.WidthRequest = 80;
			this.filechooserbutton2.Name = "filechooserbutton2";
			this.fixed1.Add (this.filechooserbutton2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.filechooserbutton2]));
			w2.X = 680;
			w2.Y = 58;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Choose a file");
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w3.X = 680;
			w3.Y = 28;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Original Content");
			this.fixed1.Add (this.label2);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
			w4.X = 36;
			w4.Y = 28;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.WidthRequest = 280;
			this.GtkScrolledWindow2.HeightRequest = 110;
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.textview4 = new global::Gtk.TextView ();
			this.textview4.CanFocus = true;
			this.textview4.Name = "textview4";
			this.GtkScrolledWindow2.Add (this.textview4);
			this.fixed1.Add (this.GtkScrolledWindow2);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow2]));
			w6.X = 36;
			w6.Y = 356;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button3 = new global::Gtk.Button ();
			this.button3.WidthRequest = 80;
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("Encrypt");
			this.fixed1.Add (this.button3);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button3]));
			w7.X = 680;
			w7.Y = 116;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button4 = new global::Gtk.Button ();
			this.button4.WidthRequest = 80;
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString ("Decrypt");
			this.fixed1.Add (this.button4);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button4]));
			w8.X = 680;
			w8.Y = 174;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.WidthRequest = 476;
			this.statusbar1.HeightRequest = 20;
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.fixed1.Add (this.statusbar1);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.statusbar1]));
			w9.X = 36;
			w9.Y = 490;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.WidthRequest = 280;
			this.GtkScrolledWindow.HeightRequest = 110;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview2 = new global::Gtk.TextView ();
			this.textview2.CanFocus = true;
			this.textview2.Name = "textview2";
			this.GtkScrolledWindow.Add (this.textview2);
			this.fixed1.Add (this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
			w11.X = 36;
			w11.Y = 50;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Deciphered Text");
			this.fixed1.Add (this.label4);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
			w12.X = 36;
			w12.Y = 336;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Ciphered Text");
			this.fixed1.Add (this.label3);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
			w13.X = 36;
			w13.Y = 190;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.WidthRequest = 280;
			this.GtkScrolledWindow1.HeightRequest = 110;
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.textview3 = new global::Gtk.TextView ();
			this.textview3.CanFocus = true;
			this.textview3.Name = "textview3";
			this.GtkScrolledWindow1.Add (this.textview3);
			this.fixed1.Add (this.GtkScrolledWindow1);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow1]));
			w15.X = 36;
			w15.Y = 210;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.WidthRequest = 208;
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = false;
			this.entry1.InvisibleChar = '●';
			this.fixed1.Add (this.entry1);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry1]));
			w16.X = 414;
			w16.Y = 50;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry2 = new global::Gtk.Entry ();
			this.entry2.WidthRequest = 208;
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = false;
			this.entry2.InvisibleChar = '●';
			this.fixed1.Add (this.entry2);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry2]));
			w17.X = 414;
			w17.Y = 111;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Hash for original text");
			this.fixed1.Add (this.label5);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
			w18.X = 414;
			w18.Y = 28;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Hash for deciphered text");
			this.fixed1.Add (this.label6);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
			w19.X = 414;
			w19.Y = 88;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Public Key");
			this.fixed1.Add (this.label7);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label7]));
			w20.X = 414;
			w20.Y = 162;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry3 = new global::Gtk.Entry ();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = false;
			this.entry3.InvisibleChar = '●';
			this.fixed1.Add (this.entry3);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry3]));
			w21.X = 414;
			w21.Y = 188;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry4 = new global::Gtk.Entry ();
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = false;
			this.entry4.InvisibleChar = '●';
			this.fixed1.Add (this.entry4);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry4]));
			w22.X = 414;
			w22.Y = 262;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Private Key");
			this.fixed1.Add (this.label8);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label8]));
			w23.X = 414;
			w23.Y = 232;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 852;
			this.DefaultHeight = 562;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.button1.Released += new global::System.EventHandler (this.OnButton1Released);
			this.filechooserbutton2.SelectionChanged += new global::System.EventHandler (this.OnFilechooserbutton2SelectionChanged);
			this.button3.Released += new global::System.EventHandler (this.OnButton3Released);
			this.button4.Released += new global::System.EventHandler (this.OnButton4Released);
		}
	}
}
