<div class="hot">
<a href="http://imgur.com/ZSGb4jr"><img src="http://i.imgur.com/ZSGb4jr.jpg" title="Hosted by imgur.com"/></a>
<p><strong>Australia had long been on my mind before I finally set my foot on the continent that later should become my new home.</strong><br /> <br />
But before accidentally immigrating and  settling down in a tiny town in the middle of the rainforest living the life of a 21st century female Tarzan in paradise there were over two years and some 60 000 km on the road to be travelled to get to know the country. I started my trip civilized in a big city called Melbourne, famous for its culture and European style. 
There I worked as a volunteer for the National Parks of Victoria before buying a proper 4WD that, at that time, reminded me of a moon ferry. It was the first car I ever owned (and pretty much the first car I had ever driven). At that time I thought a massive Toyota Landcruiser with piles of recovery gear really was a bit of an  overkill for a girl that wanted to travel around Australia, but once I had this big machine I might as well use it. So I set off for an adventure… and another one… and another one.</p>    

<p>19 flat tyres and countless stories later I can now say that I know every single square inch of a country that is so diverse and huge that it might as well take a life time to get to know it well (and I know how to change tyres!).</p>

<p>No matter what time of the year you travel, there’s always a part of Australia that would have nearly perfect travel conditions. As a general rule you can say that the north and the centre are best to be explored during the Australian winter between May and September while the south has its peak season in summer between October and April.  Winter in the tropical north is the dry season when there’s not much rain and the temperature is very pleasant, while winter in the south can be quite chilly and rainy.</p>
<p>The tropical summer with the wet season can bring humidity that makes the air getting stuck in your nostrils and parts of your body sweat that you had no idea about they could.  You also have to expect extreme downpours, floods and the occasional road closure. However, with a few exceptions the major sights of the north can still be travelled, there is no need to freak out, just be prepared to change your plans a little bit according to the weather. It’s the time of the year that shows off spectacular extremes of nature, the time that belongs to the locals.</p>
<a href="http://imgur.com/266zKzW"><img src="http://i.imgur.com/266zKzW.jpg" title="Hosted by imgur.com"/></a>
<p>In the centre and in the south the temperature can become very hot in summer. We are speaking of 45 degrees or more in the outback. Make sure your car has air condition, otherwise you will tell stories like me where we crossed the outback in summer in a VERY hot car. The drinking water in our bottles boiled, and when we put tea bags in it turned into tea – but it was and stayed too hot to drink!!!</p>

<p>Australia offers a huge diversity of landscapes and places worth a visit. It ranges from the big cities like Sydney and Melbourne with their skyscrapers, rugged coast lines and parks to vast eucalypt forests, some occupied by cuddly koalas or inquisitive kangaroos. I’ve been to places where over 100 of these hopping creatures would sit on the grass every evening – OUR grass as we thought as that was the place where we used to play Frisbee. To our delight and annoyance said kangaroos were so used to humans that they would never go out of the way and we kept tripping over them when chasing our flying disk. Tasmania and the Australian Alps offer you spectacular mountain scenery and, yep, snow in winter. The east coast stretches along countless beautiful islands, and countless backpackers stretch on its beautiful beaches. The far north around Cairns is certainly a highlight on any Australian trip. Nowhere else you have such a diversity of landscapes on a relatively small scale. This is where you go diving and chasing sea turtles in the Great Barrier Reef, where you walk through ancient rainforests, where you finally get to play Robinson Crusoe on endless paradise like beaches and where you realise how hard it is to open a coconut - unless you know how to do it.  For the adventurous ones there's still another 1000 km to the northern tip of the continent. But to go there you need a 4WD and solid knowledge on how to use it. We crossed deep creeks and log bridges so wobbly and narrow that the logs on one end would flip up the moment you put the weight of the vehicle on the other end, and the bridge was 5 (five!!!) cm wider than the car! The so called Top End around Darwin with the Kakadu National Park rewards you with countless waterfalls and plenty of wildlife. Just be careful where you go for a swim there. Saltwater crocodiles inhabit these waterways and they don’t mix very well with humans.  You don’t want to see a “saltie” chasing your travel mate… While, actually, with a happy ending that makes a perfect party story – ask me. Western Australia stuns you with mind blowing gorges the bluest water in the ocean and so many miles on the highways that they even use the roads as airstrips, so you better watch out for aerial traffic. Last but not least there is what makes the majority of the Australian landmass, the “middle of nowhere”, the outback, that vast, dry emptiness that is known for its red sand, endlessness and the occasional quirky roadhouse to break up your long drive with displays of snakes preserved in alcohol jars, photos of unusual accidents and roadtrain drivers in blue singlets (and the worst Australian accent) to tell you about their life in a truck the size of a train driving 1200 kilometres on highways every day whilst watching DVDs. And finally you will stand in front of Uluru, formerly known as Ayers Rock, and it will take your breath away as it has been doing with me every time I visit this sacred place.</p>
<a href="http://imgur.com/FdoCCw2"><img src="http://i.imgur.com/FdoCCw2.jpg" title="Hosted by imgur.com"/></a> 

<p>Australia might look small on a map. In fact, it’s the size of the USA. And the distances are endless and longer. The most common mistake I see in Europeans travelling around Australia is underestimating the vastness. Eventually, when you come across a sign that states “next fuel 650 km” or  “direction to the nearest (!!!) town: turn left after 700 km”, you realise that in Europe you would have crossed 3 countries by then. In Australia you drive the same distance just to get to the next takeaway coffee. You have countless options to travel: bus, hired car or camper van, own car, train, plane or maybe you manage to ride on a kangaroo. You can go on guided tours, find travel mates to share a ride with or do a solo trip.  While for anyone with enough time (anything over 2 months) I highly recommend getting your own transport, for shorter holidays I can’t stress enough that you will get more out of the country if you focus on 2-3 hot spots and fly in between rather than try to tick as many sights as possible. By trying to see everything you will see nothing. My choice of freedom and travel style is getting a 4WD with a bed in the back. That way you can often camp wherever you are and you can go almost anywhere – ok, that depends on your driving and recovery skills. Anyone, who seriously considers to cross deep creeks in a car, burrow himself in soft sand or send his vehicle over massive boulders that make the wheels spin in the air should know what he is doing, otherwise you risk your car or your life. But the photo of your recovery is guaranteed to end up in the next roadhouse on the wall for generations of locals to laugh at you! The places where we stayed overnight in my car would make anyone jealous. We overlooked endless white beaches, were surrounded by bush fires, had our camp fires under the starry sky or woke up in the morning just to find out that the stalls of the weekend market had miraculously appeared around us whilst we were sleeping so that we stood in our pyjamas in the middle of a hustling market. I had wallabies jumping on top of my roof and I had sprinklers that magically rose from the grass in the middle of the night setting my car under water through the open windows (first I thought it was raining until I realised that I had parked my car on a well watered lawn).</p>
<a href="http://imgur.com/qX4xU6s"><img src="http://i.imgur.com/qX4xU6s.jpg" title="Hosted by imgur.com"/></a>
<p>Many people hesitate to travel to Australia as it is well know that absolutely everything here is going to kill you: sharks and crocodiles will have you for dinner, whatever they leave behind will get killed by a jelly fish, a blue ring octopus or a cone shell. So don't enter the water. On land deadly snakes and spiders wait for you behind every corner and even touching some plants will inflict serious pain. So you better stay in the house cuddled up in a blanket and hope that no centipede is hiding inside the latter. But have you ever wondered how Australians can survive in this murderous country? In fact, Australia is as dangerous as you make it. Swimming in croc infested rivers is not the smartest thing to do, but swallowing a wasp that flew into your sweet drink in Europe is just as deadly. As everywhere: If you read (and obey!) the warning signs that are in place wherever applicable (and there will be more than necessary) you will be safe. In fact, Australians are super safety conscious. There's rules and regulations for everything. The full impact of this policy hit me when I worked alongside park rangers and had to go through countless safety instructions where we learned how to use.... wait, are you ready?... a pencil safely! And believe me, you are far more likely to get killed by a coconut falling onto your head than even seeing one of those deadly animals.</p>

<p>For me Australia is an endless source of freedom, it filled my life with more memories than I would have ever imagined and as I am living here now I still enjoy that I can have a work life (far from a normal office job) that allows me to spend my weekends camping next to a waterfall or diving the Great Barrier Reef.</p>
<a href="http://imgur.com/peUNZ9B"><img src="http://i.imgur.com/peUNZ9B.jpg" title="Hosted by imgur.com"/></a>
<p style="margin-top:6px"><a href="#" onClick="history.go(-1)">Previous Page</a> | see also: <?php echo anchor('regions/australia', 'Australia') ?></p>
</div>
<div class="clear"></div>
<div class="comment">
<img src="<?php echo base_url() ?>assets/images/comments.png" alt="comment" style="margin-left:300px" /><?php echo anchor('user/make_comment/angie', 'Leave a comment') ?>
</div>